### ISSUE TITLE
can't run npm run dev in laravel/nova

### ISSUE THREAD

**Issue by nerdcel** [laravel/nova-issues#1119]
I want to develop a new nova-component and try to use the vue dev-tools. So I renamed the webpack.mix.js in vendor/laravel/nova to run the development script and publish the assets, as described [here](https://github.com/laravel/nova-issues/issues/33)
But when I run npm run dev I get the following error:

`> @ development /myuser/Sites/my-project/vendor/laravel/nova
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/myuser/Sites/my-project/vendor/laravel/nova/node_modules/webpack-cli/bin/cli.js:244
                throw err;
                ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at mergeObject (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/deepmerge/dist/umd.js:55:9)
    at deepmerge (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/deepmerge/dist/umd.js:79:10)
    at reduce (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/babel-merge/dist/index.js:30:44)
    at Array.reduce (<anonymous>)
    at mergeArray (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/babel-merge/dist/index.js:20:36)
    at babelMerge (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/babel-merge/dist/index.js:41:19)
    at values.reduce (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/babel-merge/dist/index.js:60:26)
    at Array.reduce (<anonymous>)
    at Function.value (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/babel-merge/dist/index.js:58:49)
    at Function.generate (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/laravel-mix/src/BabelConfig.js:11:22)
    at Object.babel (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/laravel-mix/src/config.js:121:45)
    at JavaScript.webpackRules (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/laravel-mix/src/components/JavaScript.js:74:41)
    at ComponentFactory.applyRules (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/laravel-mix/src/components/ComponentFactory.js:154:23)
    at Mix.listen.rules (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/laravel-mix/src/components/ComponentFactory.js:65:48)
    at events.(anonymous function).forEach.handler (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/laravel-mix/src/Dispatcher.js:34:47)
    at Array.forEach (<anonymous>)
    at Dispatcher.fire (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/laravel-mix/src/Dispatcher.js:34:28)
    at Mix.dispatch (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/laravel-mix/src/Mix.js:104:25)
    at WebpackConfig.buildRules (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/laravel-mix/src/builder/WebpackConfig.js:83:13)
    at WebpackConfig.build (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/laravel-mix/src/builder/WebpackConfig.js:23:14)
    at Object.<anonymous> (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/laravel-mix/setup/webpack.config.js:29:38)
    at Module._compile (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /myuser/Sites/my-project/vendor/laravel/nova/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/webpack-cli/bin/cli.js:241:39)
    at Object.parse (/myuser/Sites/my-project/vendor/laravel/nova/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /myuser/.npm/_logs/2018-12-12T08_05_54_892Z-debug.log`

Does anyone have a fix for this?

**Comment by davidhemphill** [comment]
In your Tool, can you add this:

```js
Vue.config.devtools = true
```

I'm wondering if this will enable devtools for you.

**Comment by nerdcel** [comment]
> In your Tool, can you add this:
> 
> ```js
> Vue.config.devtools = true
> ```
> 
> I'm wondering if this will enable devtools for you.

Sadly that's not working. I'm wondering why I can't run the npm run commands. I installed all packages with no errors.

**Comment by davidhemphill** [comment]
This isn't explicitly supported, but you do need to copy the `webpack.mix.js.dist` over to `webpack.mix.js`. Have you done that?

**Comment by nerdcel** [comment]
Yes I did that. Funny is, that I did this before and it worked, but since I updated Nova it's not working anymore. Could be an coincidence. And yes, i copied the webpack.mix.js again after i updated.

Btw. I'm running node 9.5.0 and npm 5.6.0

**Comment by webhealer** [comment]
I tested it.  i can able to run **npm run development**  inside nova folder, without any issue. 
vue dev-tools enabled.

node version: 10.4.1
npm version: 6.4.1
nova version : 1.2.1

@nerdcel may be you should try to remove  node_modules folder. and re install modules:
```
rm -rf node_modules/
npm i
```
then you can try to do :

```
npm run development
php artisan nova:publish

```
![vue-dev-2](https://user-images.githubusercontent.com/701360/49897763-178d7300-fe68-11e8-88d6-899e7458f701.png)
![vue-dev-1](https://user-images.githubusercontent.com/701360/49897764-18260980-fe68-11e8-90f5-ad5b00cfd27e.png)

**Comment by webhealer** [comment]
btw,  nova/package.json not included "pikaday" module . need to do npm install --save pikaday

**Comment by admench** [comment]
I had to `yarn add pikaday` also - seems to be missing from package.json in `vendor/laravel/nova`

**Comment by nerdcel** [comment]
I updated laravel-nova and added pikaday to my package.json. Now it seems to work. Thanks for all your help

**Comment by cameron-elliott** [comment]
I had the a similar situation  where 'npm run dev' was not working from the nova directory,
and had to do the following to be able to get 'npm run dev' working.

```bash
rm -rf node_modules/
npm i
cp webpack.mix.js.dist webpack.mix.js
npm run development
```


Leaving this in case it helps others, or myself after I forget how I fixed it.
(please backup before trying this)
