### ISSUE TITLE
Can create new `card` resource but not working

### ISSUE THREAD

**Issue by Ange7** [laravel/nova-issues#1274]
- Laravel Version: 5.7
- Nova Version: 1.3.1
- PHP Version: 7
- Operating System and Version: Debian

### Description:

I can create new card but i have a problem with npm run so i can't use it

### Steps To Reproduce:

1. php artisan nova:card Mycompa/Test 
i have this error during installation : 

> ERROR in ./resources/js/card.js
Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/data/project/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/data/project/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/data/project/node_modules/@babel/plugin-proposal-decorators/lib/index.js:43:7)
    at /data/project/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/data/project/nova-components/Test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/data/project/nova-components/Test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /data/project/nova-components/Test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/data/project/nova-components/Test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/data/project/nova-components/Test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/data/project/nova-components/Test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/data/project/nova-components/Test/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/data/project/nova-components/Test/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/data/project/nova-components/Test/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/data/project/nova-components/Test/node_modules/babel-loader/lib/index.js:50:20)
    at /data/project/nova-components/Test/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/data/project/nova-components/Test/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
 @ multi ./resources/js/card.js ./resources/sass/card.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

so on google i found the solution : `npm install babel-loader babel-core@^7.0.0-bridge @babel/core --save-dev` 

But now i have error : 

> ERROR in ./resources/js/card.js
Module build failed: TypeError: this.setDynamic is not a function
    at PluginPass.pre (/data/project/nova-components/Test/node_modules/babel-plugin-transform-runtime/lib/index.js:31:12)
    at transformFile (/data/project/nova-components/Test/node_modules/@babel/core/lib/transformation/index.js:78:27)
    at runSync (/data/project/nova-components/Test/node_modules/@babel/core/lib/transformation/index.js:45:3)
    at runAsync (/data/project/nova-components/Test/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at process.nextTick (/data/project/nova-components/Test/node_modules/@babel/core/lib/transform.js:34:34)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ multi ./resources/js/card.js ./resources/sass/card.scss

So my new card can't work. and i didn't found solution for this problem... 

Thanks

**Comment by Ange7** [comment]
it's package.json in my nova-component/Test/

`{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "@babel/core": "^7.2.2",
        "babel-core": "^7.0.0-bridge.0",
        "babel-loader": "^8.0.5",
        "cross-env": "^5.0.0",
        "laravel-mix": "^1.0"
    },
    "dependencies": {
        "vue": "^2.5.0"
    } 
}
`

**Comment by dkulyk** [comment]
laravel mix 1.* uses babel 6. you need to upgrade to mix 4 for using babel 7

**Comment by TimothePearce** [comment]
@Ange7 You can moves all your `@babel/*` and `sass` dependencies to `devDependencies` as they are used with `laravel-mix` and `webpack`.
