### ISSUE TITLE
Error when edit a item (resource) with a computed field

### ISSUE THREAD

**Issue by abkrim** [laravel/nova-issues#1316]
- Laravel Version: 5.7.24
- Nova Version: 1.3.1
- PHP Version: 7.2.14
- Operating System and Version: MacOs 10.13.6
- Browser type and version: Opera 57.0.3098.116

### Description:
When use a computed field in a resoource, when try to edit item of resource get error. Computed fields is not editable. (try onlyOnIndex() and others methods)

### Steps To Reproduce:

1. Data for testing
```json
{"id":31920,"unsplash_id":"nS7FU8CMmiA","description":"naturaleza monta\u00f1a al aire libre cordillera hielo","urls":"{\"raw\": \"https:\/\/images.unsplash.com\/photo-1542325177246-5085a581bd6b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjQ5NzYwfQ\", \"full\": \"https:\/\/images.unsplash.com\/photo-1542325177246-5085a581bd6b?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjQ5NzYwfQ\", \"small\": \"https:\/\/images.unsplash.com\/photo-1542325177246-5085a581bd6b?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjQ5NzYwfQ\", \"thumb\": \"https:\/\/images.unsplash.com\/photo-1542325177246-5085a581bd6b?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjQ5NzYwfQ\", \"regular\": \"https:\/\/images.unsplash.com\/photo-1542325177246-5085a581bd6b?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjQ5NzYwfQ\"}","acknowledgement":"{\"html\": \"https:\/\/unsplash.com\/photos\/nS7FU8CMmiA\", \"self\": \"https:\/\/api.unsplash.com\/photos\/nS7FU8CMmiA\", \"user\": \"https:\/\/unsplash.com\/@daniel_kessin_photo\", \"download\": \"https:\/\/unsplash.com\/photos\/nS7FU8CMmiA\/download\", \"download_location\": \"https:\/\/api.unsplash.com\/photos\/nS7FU8CMmiA\/download\"}","created_at":"2019-02-01 08:27:12","updated_at":"2019-02-01 08:27:12"}
```

2. Code of Nova resource
```php
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;
use Illuminate\Http\Request;
use Laravel\Nova\Panel;
use Spatie\TagsField\Tags;

    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Unsplash','unsplash_id')->hideWhenUpdating(),
            Text::make('Title', 'description'),

            new Panel('Tags', $this->tagsFields()),

            new Panel('Photo', $this->photoFields()),
            
        ];
    }
    protected function photoFields()
    {
        return [
            Text::make('urls', function () {
                $data = json_decode($this->urls);
                return $data->regular;
            })->onlyOnIndex()
        ];
    }

    protected function tagsFields()
    {
        return [
            Tags::make('Tags'),
        ];
    }
   ...
```
   
Error of screen 
![pantalla_completa_1_2_19_9_40](https://user-images.githubusercontent.com/1238625/52112037-a10a2780-2605-11e9-8a02-0c0dd12bb55d.jpg)

Error log

```
[2019-02-01 08:40:26] local.ERROR: Trying to get property 'regular' of non-object {"userId":1,"email":"abdelkarim.mateos@castris.com","exception":"[object] (ErrorException(code: 0): Trying to get property 'regular' of non-object at /Users/abkrim/Sites/multimedia/app/Nova/Photo.php:114)
[stacktrace]
#0 /Users/abkrim/Sites/multimedia/app/Nova/Photo.php(114): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/Users/abkrim/S...', 114, Array)
#1 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/Fields/Field.php(207): App\\Nova\\Photo->App\\Nova\\{closure}()
#2 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/Fields/Field.php(173): Laravel\\Nova\\Fields\\Field->resolveComputedAttribute(Object(Closure))
#3 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): Laravel\\Nova\\Fields\\Field->resolve(Object(App\\Photo))
#4 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Support/Collection.php(418): Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Laravel\\Nova\\Fields\\Text), 4)
#5 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->each(Object(Closure))
#6 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/ResolvesFields.php(165): Illuminate\\Support\\HigherOrderCollectionProxy->__call('resolve', Array)
#7 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1027): Laravel\\Nova\\Resource->Laravel\\Nova\\{closure}(Object(Laravel\\Nova\\Fields\\FieldCollection))
#8 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/ResolvesFields.php(166): tap(Object(Laravel\\Nova\\Fields\\FieldCollection), Object(Closure))
#9 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/ResolvesFields.php(122): Laravel\\Nova\\Resource->resolveFields(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest))
#10 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/PerformsValidation.php(103): Laravel\\Nova\\Resource->updateFields(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest))
#11 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/PerformsValidation.php(87): Laravel\\Nova\\Resource::rulesForUpdate(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest))
#12 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/PerformsValidation.php(76): Laravel\\Nova\\Resource::validatorForUpdate(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest))
#13 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/Http/Controllers/ResourceUpdateController.php(25): Laravel\\Nova\\Resource::validateForUpdate(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest))
#14 [internal function]: Laravel\\Nova\\Http\\Controllers\\ResourceUpdateController->handle(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest), 'photos', '31920')
#15 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#16 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('handle', Array)
#17 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Nova\\Http\\Controllers\\ResourceUpdateController), 'handle')
#18 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#19 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#20 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/Http/Middleware/Authorize.php(18): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Nova\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Nova\\Http\\Middleware\\BootTools->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/Http/Middleware/DispatchServingNovaEvent.php(20): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#55 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#56 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#57 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#58 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/abkrim/Sites/multimedia/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/abkrim/Sites/multimedia/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#79 /Users/abkrim/Sites/multimedia/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#80 /Users/abkrim/Sites/multimedia/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#81 /Users/abkrim/.composer/vendor/laravel/valet/server.php(158): require('/Users/abkrim/S...')
#82 {main}
"}
```

**Comment by dkulyk** [comment]
@davidhemphill I'll fix it in https://github.com/laravel/nova/pull/219 on next week.

**Comment by abkrim** [comment]
Thanks.

**Comment by dkulyk** [comment]
PR wa sent to upstream.

**Comment by shalawani** [comment]
any porgress here ?

**Comment by kirya-dev** [comment]
+1
Problem has also when resource creating!
Please fix.. now, i need use `$this->exists ? $this->property :null;`
It`s not frendly for creating

**Comment by kirya-dev** [comment]
Problem reproduce also for ComputedField

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.
