### ISSUE TITLE
Can't delete image on HasMany relationships edited through parent, with `&viaRelationship=` url param.

### ISSUE THREAD

**Issue by geraintp** [laravel/nova-issues#1819]
- Laravel Version: 5.8.31
- Nova Version: 2.0.10
- PHP Version: 7.2
- Database Driver and Version: MySQL 5.7
- Operating System and Version: OSX 10.14
- Browser type and version: Chrome 76

- Reproduction Repository:   to follow.

### Description

Clicking on the edit, resource item button, adds the url param 'viaRelationship' eg.. 
`via?viaResource=retailers&viaResourceId=1368&viaRelationship=offers`

eg. when editing an offer, belonging to a Retailer.

If that resource has an image the delete/button does not work, it generated a 500 error

`Call to undefined method App\Offer::offers()` 

removing the viaRelationship param, clicking view resource item and then edit icon or visiting the resource (offer) item directly all function correctly and successfully removes the image.

### Steps To Reproduce

Have a resource with a hasMany child resources with an image property.  
Eg. A Retailer HasMany Offers.

View a Retailer, and then click edit on one of the offers.
try and delete the the image using the delete method under the image.

```json
{
    "message": "Call to undefined method App\\Offer::offers()",
    "exception": "BadMethodCallException",
    "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php",
    "line": 50,
    "trace": [
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php",
            "line": 36,
            "function": "throwBadMethodCallException",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "::"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
            "line": 1618,
            "function": "forwardCallTo",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/nova/src/Http/Requests/PivotFieldDestroyRequest.php",
            "line": 62,
            "function": "__call",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/spatie/once/src/functions.php",
            "line": 22,
            "function": "Laravel\\Nova\\Http\\Requests\\{closure}",
            "class": "Laravel\\Nova\\Http\\Requests\\PivotFieldDestroyRequest",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/nova/src/Http/Requests/PivotFieldDestroyRequest.php",
            "line": 66,
            "function": "once"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/nova/src/Http/Requests/PivotFieldDestroyRequest.php",
            "line": 18,
            "function": "findRelatedModel",
            "class": "Laravel\\Nova\\Http\\Requests\\PivotFieldDestroyRequest",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/nova/src/Http/Controllers/PivotFieldDestroyController.php",
            "line": 20,
            "function": "authorizeForAttachment",
            "class": "Laravel\\Nova\\Http\\Requests\\PivotFieldDestroyRequest",
            "type": "->"
        },
        {
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Controllers\\PivotFieldDestroyController",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 219,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 176,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 680,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/nova/src/Http/Middleware/Authorize.php",
            "line": 18,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\Authorize",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/nova/src/Http/Middleware/BootTools.php",
            "line": 20,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\BootTools",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/nova/src/Http/Middleware/DispatchServingNovaEvent.php",
            "line": 20,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php",
            "line": 43,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/nova/src/Http/Middleware/Authenticate.php",
            "line": 31,
            "function": "handle",
            "class": "Illuminate\\Auth\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php",
            "line": 75,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 56,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php",
            "line": 66,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 682,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 657,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 623,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 612,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 176,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/nova/src/Http/Middleware/ServeNova.php",
            "line": 26,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Laravel\\Nova\\Http\\Middleware\\ServeNova",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 62,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 151,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 116,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/Users/geraint/Desktop/GIT/plantpot/public/index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/Users/geraint/.composer/vendor/laravel/valet/server.php",
            "line": 158,
            "function": "require"
        }
    ]
}```

**Comment by sirikkoster** [comment]
I had the same problem https://github.com/laravel/nova-issues/issues/1801 , no solution !.

**Comment by king724** [comment]
I also have this issue.

**Comment by chinleung** [comment]
I'm also having the same issue here. Is there any ETA for the fix?

**Comment by Yannik-Slym** [comment]
Any news on this ? Same issue with 2.9.2 nova.

**Comment by jbrooksuk** [comment]
Confirmed. I'll investigate.

**Comment by Yannik-Slym** [comment]
@jbrooksuk Any news on this ?

**Comment by LegitDongo** [comment]
I'm having this issue as well, seems to be semi-random, but always happens when clicking delete on the file field in the form.
This applies to both Image and File fields.

**Comment by tumispro** [comment]
I have this issue as well (v2.11.1). Seems to happen at random and it seems to be calling a relationship of its parent (in my case it calls `downloads()` relation on an item, while that's a relation that exists on its parent only.

Trace:

`
ERROR: Call to undefined method App\Nova\Models\ListDirectoryItemDownload::downloads() {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method App\\Nova\\Models\\ListDirectoryItemDownload::downloads() at XXX/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50)
[stacktrace]
#0 XXX/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException('downloads')
#1 XXX/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1614): Illuminate\\Database\\Eloquent\\Model->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'downloads', Array)
#2 XXX/vendor/laravel/nova/src/Http/Requests/PivotFieldDestroyRequest.php(62): Illuminate\\Database\\Eloquent\\Model->__call('downloads', Array)
#3 XXX/vendor/spatie/once/src/functions.php(27): Laravel\\Nova\\Http\\Requests\\PivotFieldDestroyRequest->Laravel\\Nova\\Http\\Requests\\{closure}(Array)
#4 XXX/vendor/laravel/nova/src/Http/Requests/PivotFieldDestroyRequest.php(66): once(Object(Closure))
#5 XXX/vendor/laravel/nova/src/Http/Requests/PivotFieldDestroyRequest.php(18): Laravel\\Nova\\Http\\Requests\\PivotFieldDestroyRequest->findRelatedModel()
#6 XXX/vendor/laravel/nova/src/Http/Controllers/PivotFieldDestroyController.php(20): Laravel\\Nova\\Http\\Requests\\PivotFieldDestroyRequest->authorizeForAttachment()
#7 [internal function]: Laravel\\Nova\\Http\\Controllers\\PivotFieldDestroyController->handle(Object(Laravel\\Nova\\Http\\Requests\\PivotFieldDestroyRequest), 'list-directory-...', '1074', 'undefined', 'undefined', 'file')
`

**Comment by anotherfrontendguy** [comment]
Hey, I ran into the same issue today. 

My Setup:

- Laravel Version: v7.14.1
- Nova Version: 3.6.0
- PHP Version: 7.3.10
- Database Driver and Version: MySQL 5.7.27

I created reproduction repository here:
https://github.com/anotherfrontendguy/nova-test

Here is a quick demo of that repo (with the issue other people here were already describing):

![demo](https://user-images.githubusercontent.com/4764281/83642361-07fb7000-a5af-11ea-99e7-a0bc963bab10.gif)

Confirming the delete action results in the following request:

<img width="1704" alt="Screenshot 2020-06-03 at 15 27 15" src="https://user-images.githubusercontent.com/4764281/83642176-c9fe4c00-a5ae-11ea-87ef-eb41b3a1c748.png">

My best guess is, this has something to do with these lines in the Nova File Field:
```js
// resources/js/components/Form/FileField.vue:207
const uri = this.viaRelationship
    ? `/nova-api/${resourceName}/${resourceId}/${relatedResourceName}/${relatedResourceId}/field/${attribute}?viaRelationship=${viaRelationship}`
    : `/nova-api/${resourceName}/${resourceId}/field/${attribute}`
```

**Comment by thoresuenert** [comment]
@anotherfrontendguy the problem in that context is:

The first route is used an handled by the pivot controller:

```
  PivotFieldDestroyController
```

But its not a Pivot Field ;)

**Comment by YannikFirre** [comment]
Hello @jbrooksuk ! 

Any news or workaround ? 

Thanks :)
