### ISSUE TITLE
Error when displaying filled MorphTo relation in form

### ISSUE THREAD

**Issue by salomonsanz** [laravel/nova-issues#1869]
- Laravel Version: 5.8.33
- Nova Version: 2.1.1
- PHP Version: 7.1.23

### Description

The error happens when Nova shows in form a Model that has MorphTo relation filled.
In detail/form throws this error and breaks the js:
<img width="1081" alt="Captura de pantalla 2019-08-29 a las 13 07 59" src="https://user-images.githubusercontent.com/24811202/63935616-264fa080-ca5e-11e9-85cd-6418262e9543.png">
with this log
```
#7 /Users/salomon/Desktop/webs/mynovaproject/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(505): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#8 /Users/salomon/Desktop/webs/mynovaproject/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#9 /Users/salomon/Desktop/webs/mynovaproject/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php(83): Illuminate\\Database\\Eloquent\\Builder->first()
#10 /Users/salomon/Desktop/webs/mynovaproject/vendor/laravel/nova/src/Fields/MorphTo.php(154): Illuminate\\Database\\Eloquent\\Relations\\BelongsTo->getResults()
#11 /Users/salomon/Desktop/webs/mynovaproject/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): Laravel\\Nova\\Fields\\MorphTo->resolve(Object(App\\Models\\User))
#12 /Users/salomon/Desktop/webs/mynovaproject/vendor/laravel/framework/src/Illuminate/Support/Collection.php(475): Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Laravel\\Nova\\Fields\\MorphTo), 4)
#13 /Users/salomon/Desktop/webs/mynovaproject/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->each(Object(Closure))
#14 /Users/salomon/Desktop/webs/mynovaproject/vendor/laravel/nova/src/ResolvesFields.php(250): Illuminate\\Support\\HigherOrderCollectionProxy->__call('resolve', Array)
#15 /Users/salomon/Desktop/webs/mynovaproject/vendor/laravel/nova/src/ResolvesFields.php(58): Laravel\\Nova\\Resource->resolveFields(Object(Laravel\\Nova\\Http\\Requests\\ResourceDetailRequest), Object(Closure))
#16 /Users/salomon/Desktop/webs/mynovaproject/vendor/laravel/nova/src/ResolvesFields.php(85): Laravel\\Nova\\Resource->detailFields(Object(Laravel\\Nova\\Http\\Requests\\ResourceDetailRequest))
#17 /Users/salomon/Desktop/webs/mynovaproject/vendor/laravel/nova/src/Resource.php(333): Laravel\\Nova\\Resource->detailFieldsWithinPanels(Object(Laravel\\Nova\\Http\\Requests\\ResourceDetailRequest))
#18 /Users/salomon/Desktop/webs/mynovaproject/vendor/laravel/nova/src/Http/Controllers/ResourceShowController.php(26): Laravel\\Nova\\Resource->serializeForDetail(Object(Laravel\\Nova\\Http\\Requests\\ResourceDetailRequest))
etc...
```

In list, works perfect:
<img width="826" alt="Captura de pantalla 2019-08-29 a las 13 03 49" src="https://user-images.githubusercontent.com/24811202/63935523-ee485d80-ca5d-11e9-9d35-d0113b5892ad.png">

I checked the database, and the data it's ok:
<img width="212" alt="Captura de pantalla 2019-08-29 a las 13 11 58" src="https://user-images.githubusercontent.com/24811202/63935859-ab3aba00-ca5e-11e9-8c83-6db42b3e20fc.png">

If i empty the fields in db, the form is shown normally.
<img width="798" alt="Captura de pantalla 2019-08-29 a las 13 16 06" src="https://user-images.githubusercontent.com/24811202/63936136-619e9f00-ca5f-11e9-97ff-bc488e97df27.png">

I have this code

```
// In App\Models\User
public function userable(){
        return $this->morphTo();
}

//In App\Models\Teacher
public function user(){
        return $this->morphOne('App\Models\User', 'userable');
}

// In App\Models\Alumn
public function user(){
        return $this->morphOne('App\Models\User', 'userable');
}

// In App\Nova\User 
public static $with = ['userable'];

// in fields
MorphTo::make('Relación','userable')->types([
    \App\Nova\Alumn::class,
    \App\Nova\Teacher::class
])->nullable()
```

I think it's a Nova bug, can someone confirm?

**Comment by salomonsanz** [comment]
Ok, i found the problem.

Was caused because the fields was defined by me in the model. Removing from the model solved the problem
