### ISSUE TITLE
When I create a tool, the template page is not displayed

### ISSUE THREAD

**Issue by archisova** [laravel/nova-issues#2129]
Laravel Version: 6.2
Nova Version: ~2.0
PHP Version: 7.4rc
Operating System and Version: Ubuntu 19.10
Browser type and version: chrome

When I create a tool, the template page is not displayed.
The link in the menu appears, but the page with the template is not displayed when navigating.
Most likely, the route itself is not created for some reason.

https://yadi.sk/i/rF1LOC-n8NdffQ
https://yadi.sk/i/vJvftyuVn72Spg
https://yadi.sk/i/UhL52Ibl8-nT4g
https://yadi.sk/i/1n1GYxgQInok6A

This my Dockerfile for PHP:

```
FROM php:7.4-rc-fpm-buster

RUN apt-get update

RUN apt-get install -y curl wget git nano locales locales-all zip unzip \
    --no-install-recommends apt-utils

RUN apt-get install -y zlib1g-dev libxslt-dev libzip-dev libpq-dev \
    --no-install-recommends apt-utils

RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql

RUN docker-php-ext-install zip opcache pdo_pgsql pgsql sockets xsl intl bcmath

# Set Russian locale
ENV LANGUAGE=ru_RU:ru
ENV LANG=ru_RU.UTF-8

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install -y nodejs

ADD ./php.ini /etc/php/7.4/fpm/conf.d/90-php.ini
ADD ./php.ini /etc/php/7.4/cli/conf.d/90-php.ini

# Permission fix
RUN usermod -u 1000 www-data

EXPOSE 9000

CMD ["php-fpm"]
```

Node & NPM:

```
root@246d1f636fa6:/var/www/html# npm -v
6.12.0
root@246d1f636fa6:/var/www/html# node -v
v12.13.0
```

[Link for git movie issue](https://yadi.sk/i/nfPL9pcHdb_2AQ)

**Comment by davidhemphill** [comment]
Your Dockerfile doesn't contain any relevant information for the issue. What is the 500 error listed in the console?

**Comment by XternalSoft** [comment]
Hello,

Try this : 
In your tools folder, create en file ".babelrc" with this content :
```
{
  "plugins": []
}
```

**Comment by archisova** [comment]
> Your Dockerfile doesn't contain any relevant information for the issue. What is the 500 error listed in the console?

I attached the Dockerfile for a more detailed understanding of the problem, so that you can understand on which configuration I deployed Laravel NOVA.

**Comment by archisova** [comment]
> What is the 500 error listed in the console?

The error occurs during the loading of the application in the browser. I specifically pointed out this error, because I also can not understand why it arises.

**Comment by archisova** [comment]
> Hello,
> 
> Try this :
> In your tools folder, create en file ".babelrc" with this content :
> 
> ```
> {
>   "plugins": []
> }
> ```
> 
> (and after _**npm run dev**_ in folder)

Unfortunately did not solve the problem.

**Comment by archisova** [comment]
Am I the only one facing this problem? So this is a bug!

**Comment by archisova** [comment]
Here such errors are present:
```
GET http://portal.u.university/nova-api/styles/resources-centers net::ERR_ABORTED 500 (Internal Server Error)
portal.u.university/:19 
GET http://portal.u.university/nova-api/styles/centers net::ERR_ABORTED 500 (Internal Server Error)
portal.u.university/:20 
GET http://portal.u.university/nova-api/styles/test-tool net::ERR_ABORTED 500 (Internal Server Error)
(index):168 
GET http://portal.u.university/nova-api/scripts/resources-centers net::ERR_ABORTED 500 (Internal Server Error)
(index):169 
GET http://portal.u.university/nova-api/scripts/centers net::ERR_ABORTED 500 (Internal Server Error)
(index):170 
GET http://portal.u.university/nova-api/scripts/test-tool net::ERR_ABORTED 500 (Internal Server Error)
resources-centers:1 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
centers:1 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
test-tool:1 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```
https://i.imgur.com/SIIxF2D.png

**Comment by jbrooksuk** [comment]
Please provide the log file contents. The fact that you have a 500 error means nothing without context, sorry!

**Comment by jbrooksuk** [comment]
I've created a new Tool and it registered and works correctly:

![image](https://user-images.githubusercontent.com/246103/68702885-73351480-0581-11ea-879a-942179400783.png)

**Comment by archisova** [comment]
I don't even have a link created to my tool.

![2019-11-13_11-03](https://user-images.githubusercontent.com/2741290/68744386-90abc200-0605-11ea-8418-979611747f9d.png)

![2019-11-13_11-05](https://user-images.githubusercontent.com/2741290/68744398-96090c80-0605-11ea-94f7-a90a031f7817.png)

**Comment by archisova** [comment]
If I work on a local machine everything is correctly created, if I work in a docker container it does not work. The tool is created crookedly.

**Comment by archisova** [comment]
Some file does not exist:

```
[2019-11-13 08:34:14] local.ERROR: The file "/var/www/portal.u.university/nova-components/TestPage/src/../dist/js/tool.js" does not exist {"userId":1,"exception":"[object] (Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException(code: 0): The file \"/var/www/portal.u.university/nova-components/TestPage/src/../dist/js/tool.js\" does not exist at /var/www/portal.u.university/vendor/symfony/http-foundation/File/File.php:36)
[stacktrace]
```

**Comment by jbrooksuk** [comment]
I don't know what to tell you, sorry. This looks to be a problem with Docker and not Nova.

**Comment by archisova** [comment]
Re-checked on the local machine and as it turned out, too, does not work. Below is the stack when creating the tool.

```
 Would you like to install the tool's NPM dependencies? (yes/no) [yes]:
 > yes

npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size

> pngquant-bin@4.0.0 postinstall /opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at /opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/agubanov/.npm/_logs/2019-11-13T09_43_25_405Z-debug.log

 Would you like to compile the tool's assets? (yes/no) [yes]:
 > yes


> @ dev /opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage
> npm run development


> @ development /opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

internal/modules/cjs/loader.js:803
    throw err;
    ^

Error: Cannot find module '/opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/laravel-mix/setup/webpack.config.js'
Require stack:
- /opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/webpack/bin/convert-argv.js
- /opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:800:15)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requireConfig (/opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/webpack/bin/convert-argv.js:97:18)
    at /opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/webpack/bin/convert-argv.js:102:15)
    at /opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/webpack/bin/webpack.js:171:41
    at Object.Yargs.self.parse (/opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/yargs/yargs.js:533:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/webpack/bin/convert-argv.js',
    '/opt/docker-compose/images/portal-and-campus-for-universal-university/docker/www/portal.u.university/nova-components/TestPage/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/agubanov/.npm/_logs/2019-11-13T09_43_36_382Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/agubanov/.npm/_logs/2019-11-13T09_43_36_391Z-debug.log

 Would you like to update your Composer packages? (yes/no) [yes]:
 > yes

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing test/test-page (dev-gubanovas/create-tool-for-test-page): Source already present
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: laravel/nova
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: test/test-page
Package manifest generated successfully.

```

**Comment by archisova** [comment]
What environment do you use when developing Laravel NOVA based applications?

**Comment by archisova** [comment]
Great news! I figured out what the problem is!

![Снимок экрана от 2019-11-13 12-59-58](https://user-images.githubusercontent.com/2741290/68753133-872a5600-0615-11ea-9bf3-df7ba7735136.png)

For the history: `apt-get install libpng-dev -y --no-install-recommends`

https://github.com/imagemin/imagemin-pngquant/issues/46#issuecomment-379604951
