### ISSUE TITLE
Is there any posibility to import/use component from resource/js in Nova Tool ?

### ISSUE THREAD

**Issue by PrzemekTkaczyk** [laravel/nova-issues#2323]
Is there any correct way to use Component from Projectc/resources/js/components in Nova Tool ?
(when try to import like: ```import Component from '../../../../../resources/js...' ``` Mix failed (in fact when try to import it from any other folder than ToolFolder is the same error - like below:)

```
Module build failed: TypeError: /Users/my-comp/Projects/project/test/resources/js/components/NewComponent.vue: this.setDynamic is not a function
    at PluginPass.pre (/Users/my-comp/Projects/project/test/nova-components/Testowy/node_modules/babel-plugin-transform-runtime/lib/index.js:31:12)
    at transformFile (/Users/my-comp/Projects/project/test/node_modules/@babel/core/lib/transformation/index.js:96:27)
    at transformFile.next (<anonymous>)
    at run (/Users/my-comp/Projects/project/test/node_modules/@babel/core/lib/transformation/index.js:35:12)
    at run.next (<anonymous>)
    at Function.transform (/Users/my-comp/Projects/project/test/node_modules/@babel/core/lib/transform.js:27:41)
    at transform.next (<anonymous>)
    at step (/Users/my-comp/Projects/project/test/node_modules/gensync/index.js:254:32)
    at gen.next (/Users/my-comp/Projects/project/test/node_modules/gensync/index.js:266:13)
    at async.call.value (/Users/my-comp/Projects/project/test/node_modules/gensync/index.js:216:11)
    at errback.call (/Users/my-comp/Projects/project/test/node_modules/gensync/index.js:184:28)
    at runGenerator.errback (/Users/my-comp/Projects/project/test/node_modules/@babel/core/lib/gensync-utils/async.js:72:7)
    at val (/Users/my-comp/Projects/project/test/node_modules/gensync/index.js:108:33)
    at step (/Users/my-comp/Projects/project/test/node_modules/gensync/index.js:280:14)
    at gen.next (/Users/my-comp/Projects/project/test/node_modules/gensync/index.js:266:13)
    at async.call.value (/Users/my-comp/Projects/project/test/node_modules/gensync/index.js:216:11)
    at <anonymous>
 @ /Users/my-comp/Projects/project/test/resources/js/components/NewComponent.vue 4:21-389
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/components/Tool.vue
 @ ./resources/js/components/Tool.vue
 @ ./resources/js/tool.js
 @ multi ./resources/js/tool.js ./resources/sass/tool.scss```

**Comment by Mhany95** [comment]
Had the same error, I upgraded babel to a newer version (7), so I had to make changes to all `devDependencies` and `.babelrc` to follow the new format for babel.

To upgrade babel to 7, you can run `npx babel-upgrade --write`, but you will probably need to make extra adjustments as mentioned [here.](https://github.com/babel/babel-loader/issues/560)

However, the `laravel-mix` package used in nova was having a different babel version, so I upgraded `laravel-mix` version to `4.1.4`, which removed the old babel modules, including `babel-plugin-transform-runtime`.

This made the error disappear, but it didn't help with importing components from resource/js to nova.
Let me know if it works out for you.

**Comment by jeffochoa** [comment]
I uploaded a video about this https://twitter.com/jeffer_8a/status/1224344871215030275?s=21

**Comment by Mhany95** [comment]
@jeffochoa What we are trying to achieve is importing "custom" vue components, that we have defined in the root of our laravel project, into nova to be able to use them.

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
