### ISSUE TITLE
Running Nova in dev mode - "Uknown browser query `dead`"

### ISSUE THREAD

**Issue by rreynier** [laravel/nova-issues#2710]
- Laravel Version: 7.17.2
- Nova Version: 3.7.0
- PHP Version: 7.4
- Node: 12.31.1
- Npm: 6.12.1

### Description:
When following the steps to enable dev tools: https://nova.laravel.com/docs/3.0/customization/frontend.html#vue-devtools, an error is encountered during the build process.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- navigate to `./vendor/laravel/nova/`
- copy webpack file: `mv webpack.mix.js.dist webpack.mix.js`
- install node dependencies: `npm install`, note the warning `npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.`
- build nova: `npm run production`
- observe the error: `Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown browser query 'dead'`

I believe the laravel-mix dependency is the culprit, but I am unable to bump it to a newer version without introducing new errors. 

Here is the full error dump:
```
 ~/Projects/project/vendor/laravel/nova  npm run dev

> @ dev /Users/roeland/Projects/project/vendor/laravel/nova
> npm run development


> @ development /Users/roeland/Projects/project/vendor/laravel/nova
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 52% building modules 357/433 modules 76 active ...avel/nova/resources/js/views/Lens.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
 95% emitting

 ERROR  Failed to compile with 2 errors                                                                                                                        11:59:01 AM

 error  in ./resources/css/app.css

Module build failed: BrowserslistError: Unknown browser query `dead`
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/node_modules/browserslist/index.js:164:11
    at Array.reduce (<anonymous>)
    at resolve (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/node_modules/browserslist/index.js:132:18)
    at browserslist (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/node_modules/browserslist/index.js:224:16)
    at Browsers.parse (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/browsers.js:61:16)
    at new Browsers (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/browsers.js:52:30)
    at loadPrefixes (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/autoprefixer.js:70:24)
    at plugin (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/autoprefixer.js:81:24)
    at LazyResult.run (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:277:20)
    at LazyResult.asyncTick (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:192:32)
    at LazyResult.asyncTick (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:204:22)
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:197:27

 @ ./resources/css/app.css 4:14-141
 @ multi ./resources/js/app.js ./resources/css/app.css

 error  in ./resources/css/app.css

Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown browser query `dead`
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/node_modules/browserslist/index.js:164:11
    at Array.reduce (<anonymous>)
    at resolve (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/node_modules/browserslist/index.js:132:18)
    at browserslist (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/node_modules/browserslist/index.js:224:16)
    at Browsers.parse (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/browsers.js:61:16)
    at new Browsers (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/browsers.js:52:30)
    at loadPrefixes (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/autoprefixer.js:70:24)
    at plugin (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/autoprefixer.js:81:24)
    at LazyResult.run (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:277:20)
    at LazyResult.asyncTick (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:192:32)
    at LazyResult.asyncTick (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:204:22)
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:197:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/webpack/lib/NormalModule.js:195:19
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss-loader/lib/index.js:194:71
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

       Asset     Size  Chunks                    Chunk Names
     /app.js   3.1 MB       0  [emitted]  [big]  /app
  /vendor.js  4.52 MB       1  [emitted]  [big]  /vendor
/manifest.js  3.84 kB       2  [emitted]         /manifest

ERROR in ./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/lib??postcss!./resources/css/app.css
Module build failed: BrowserslistError: Unknown browser query `dead`
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/node_modules/browserslist/index.js:164:11
    at Array.reduce (<anonymous>)
    at resolve (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/node_modules/browserslist/index.js:132:18)
    at browserslist (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/node_modules/browserslist/index.js:224:16)
    at Browsers.parse (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/browsers.js:61:16)
    at new Browsers (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/browsers.js:52:30)
    at loadPrefixes (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/autoprefixer.js:70:24)
    at plugin (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/autoprefixer.js:81:24)
    at LazyResult.run (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:277:20)
    at LazyResult.asyncTick (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:192:32)
    at LazyResult.asyncTick (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:204:22)
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:197:27
 @ ./resources/css/app.css 4:14-141
 @ multi ./resources/js/app.js ./resources/css/app.css

ERROR in ./resources/css/app.css
Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown browser query `dead`
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/node_modules/browserslist/index.js:164:11
    at Array.reduce (<anonymous>)
    at resolve (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/node_modules/browserslist/index.js:132:18)
    at browserslist (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/node_modules/browserslist/index.js:224:16)
    at Browsers.parse (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/browsers.js:61:16)
    at new Browsers (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/browsers.js:52:30)
    at loadPrefixes (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/autoprefixer.js:70:24)
    at plugin (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/autoprefixer/lib/autoprefixer.js:81:24)
    at LazyResult.run (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:277:20)
    at LazyResult.asyncTick (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:192:32)
    at LazyResult.asyncTick (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:204:22)
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss/lib/lazy-result.js:197:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/webpack/lib/NormalModule.js:195:19
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/roeland/Projects/project/vendor/laravel/nova/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/roeland/Projects/project/vendor/laravel/nova/node_modules/postcss-loader/lib/index.js:194:71
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./resources/css/app.css
 @ multi ./resources/js/app.js ./resources/css/app.css
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/roeland/.npm/_logs/2020-06-28T17_59_02_872Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/roeland/.npm/_logs/2020-06-28T17_59_02_894Z-debug.log
```

**Comment by rreynier** [comment]
I have figured it out! For whatever reason when running `npm install` from a path which does not contain a browserlist config, it will traverse up until it finds one.  In my case my project root has a .browserlistrc file which contains:

```
last 2 major versions
not < 0.5%
not dead
not ie 11
not ie_mob 11
not OperaMini all
```

The "not dead" configuration is not available pre browserslist@3.x. 

Long term, I imagine more people will run into this since they will be using 3.x+ browserlist config syntax in their projects, causing Nova dev builds to bomb.  I suggest that we simply add a browserlist config file to the Nova repository, therefore avoiding any conflicts with the parent project.
