### ISSUE TITLE
Error after generating and displaying a custom field: DateTime::createFromFormat() expects parameter 2 to be string, int given on nova/src/Http/Controllers/StyleController.php:34

### ISSUE THREAD

**Issue by fabioi** [laravel/nova-issues#3149]
- Laravel Version: 8.20.1
- Nova Version: 3.15
- PHP Version: 7.4

### Description:

I get this error after generating and displaying a custom field. The field was just generated but nothing was edited.. When I try to display the field in the create resource view I get:

local.ERROR: DateTime::createFromFormat() expects parameter 2 to be string, int given {"userId":3,"exception":"[object] (TypeError(code: 0): DateTime::createFromFormat() expects parameter 2 to be string, int given at /Users/fabioingrasciotta/Sites/localhost/f242020/nova/src/Http/Controllers/StyleController.php:34)
[stacktrace]
#0 /Users/Sites/localhost/nova/src/Http/Controllers/StyleController.php(34): DateTime::createFromFormat('U', 1609829251)
#1 /Users/Sites/localhost/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Laravel\\Nova\\Http\\Controllers\\StyleController->show(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest), 'calendar')

**Comment by crynobone** [comment]
`nova/src/Http/Controllers/StyleController.php:34` should be the following:

```php
DateTime::createFromFormat('U', filemtime($path));
```

Which should be correct.


![image](https://user-images.githubusercontent.com/172966/103622804-2923a500-4f72-11eb-929c-bfe335b32608.png)

**Comment by crynobone** [comment]
Do you happened to use `declare(strict_types = 1);`?

**Comment by fabioi** [comment]
Still would prefer to be able to make use of the strict types mode.

**Comment by crynobone** [comment]
@fabioi v3.19.0 includes a fix to this exact issue.

**Comment by fabioi** [comment]
Thank you a lot for your help
