### ISSUE TITLE
Exception when starting a queued action in Nova due to Telescope via Horizon

### ISSUE THREAD

**Issue by potsky** [laravel/nova-issues#3243]
- Laravel Version: 8.27.0
- Nova Version: 3.21.1
- PHP Version: 8.0
- Database Driver & Version: pgsql (last version in sail)
- Operating System and Version: last version in sail

### Description:

I post this problem on nova-issues because this is the only place where it happens but the problem is perhaps related to Horizon, Laravel framework or Telescope.

👍 When launching any queued job in a controller, the action is normally executed by Horizon.
👍 When launching any queued job in a queued action in Nova with Telescope disabled, the action is normally executed by Horizon (encapsulated in the Nova action)
👎 When launching any queued job in a queued action in Nova with Telescope enabled, the action is normally executed by Horizon (encapsulated in the Nova action) but an exception is thrown without disturbing action, job execution or telescope job reporting (success).

Here are Horizon logs when the exception is thrown :

```
[2021-02-16 08:37:31][22281e34-e2af-46e6-8200-dc1d376b2b32] Processing: App\Nova\Actions\GetExternalApiQuota
[2021-02-16 08:37:31][558e6610-a084-495b-8659-e6b774ed6230] Processing: App\Jobs\GetExternalApiQuota
[2021-02-16 08:37:31] local.ERROR: Call to a member function toArray() on null {"exception":"[object] (Error(code: 0): Call to a member function toArray() on null at /var/www/html/vendor/laravel/telescope/src/Watchers/JobWatcher.php:191)
[stacktrace]
#0 /var/www/html/vendor/laravel/telescope/src/Watchers/JobWatcher.php(84): Laravel\\Telescope\\Watchers\\JobWatcher->updateBatch()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(392): Laravel\\Telescope\\Watchers\\JobWatcher->recordProcessedJob()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(237): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(590): Illuminate\\Events\\Dispatcher->dispatch()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(408): Illuminate\\Queue\\Worker->raiseAfterJobEvent()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Worker->process()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\\Queue\\Worker->runJob()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\\Queue\\Worker->daemon()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#9 /var/www/html/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\\Queue\\Console\\WorkCommand->handle()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#16 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#18 /var/www/html/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#19 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#20 /var/www/html/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#23 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#24 {main}
"}
[2021-02-16 08:37:33][558e6610-a084-495b-8659-e6b774ed6230] Processed:  App\Jobs\GetExternalApiQuota
```

We just see this Exception in logs and a `Processed: App\Nova\Actions\GetExternalApiQuota` is missing at the end.

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Install a fresh Laravel app
- Install Nova
- Install Horizon
- Install Telescope
- Create a Nova resource
- Create a Nova queued action for this resource
- Create a queued job
- Call the queued job inside the Nova queued action like this :

```php
    public function handle(ActionFields $fields, Collection $models): array
    {
        foreach ($models as $company) {
            AnyJob::dispatch($this->user, $company);
        }
        return Action::message('Ok');
    }
```

Any idea ?

**Comment by crynobone** [comment]
The issue related to `batchId` usage on Laravel Nova, Telescope assume `batchId` are an indication that it's using Batchable Queue.
