### ISSUE TITLE
Problem with MorphMany field calling non-existent getPivotClass method

### ISSUE THREAD

**Issue by admench** [laravel/nova-issues#3550]
- Laravel Version: 7.30.4
- Nova Version: 3.29
- PHP Version: 7.4.21
- Database Driver & Version: MySql 
- Operating System and Version: os x 11.5.2 / ubuntu 20 on server (issue on both)
- Browser type and version: Chrome recent

### Description:

Set up a basic MorphMany relationship using standard column names. In nova using MorphToMany field type. 

Table loads on the models in question fine. The only issue is that I get the issue pop up as a toast in nova saying:

```
Call to undefined method Illuminate\Database\Eloquent\Relations\MorphMany::getPivotClass()
```

```
#0 /vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Relations\\Relation::throwBadMethodCallException('getPivotClass')
#1 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(385): Illuminate\\Database\\Eloquent\\Relations\\Relation->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'getPivotClass', Array)
#2 /vendor/laravel/nova/src/Http/Requests/InteractsWithRelatedResources.php(112): Illuminate\\Database\\Eloquent\\Relations\\Relation->__call('getPivotClass', Array)
#3 /vendor/laravel/nova/src/Http/Controllers/ActionController.php(28): Laravel\\Nova\\Http\\Requests\\NovaRequest->pivotName()
#4 /vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Laravel\\Nova\\Http\\Controllers\\ActionController->index(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest), 'notification-lo...')
#5 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#6 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Nova\\Http\\Controllers\\ActionController), 'index')
#7 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#8 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()

```

As you see `InteractsWithRelatedResources:112` seems to be the culprit here.

Any tips to avoid this? Will it require a nova patch or can I do something locally?

#### Local setup:

```
// User model:

public function notification_logs()
    {
        return $this->morphMany(NotificationLog::class, 'loggable');
    }

// Nova User resource:

MorphToMany::make('Notification logs'),

// NotificationLog model:

public function loggable()
    {
        return $this->morphTo();
    }

// Nova NotificationLog resource:

MorphTo::make('Loggable'),

```

Many thanks
Adam

**Comment by crynobone** [comment]
Please provide full repository to help us debug your exact use case.

**Comment by admench** [comment]
Sure I will copy relevant migrations and files to publicly accessible repo
