### ISSUE TITLE
Can't install npm dependencies for tools

### ISSUE THREAD

**Issue by flemming-petersen** [laravel/nova-issues#3686]
- Laravel Version: 8,65
- Nova Version: ~3.0
- PHP Version: 7.4
- node 16.13.1
- npm 8.1.3
- Database Driver & Version: mysql_pdo 
- Operating System and Version: alpine 3.15
- Browser type and version: Chrome

### Description:

I want to create new tool.
https://nova.laravel.com/docs/3.0/customization/tools.html

Everything worked fine until I got this error while installing the npm dependencies.

```
npm ERR! code 1
npm ERR! path /var/www/html/nova-components/VideoImport/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/bin/node /var/www/html/nova-components/VideoImport/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/var/www/html/nova-components/VideoImport/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "/usr/bin/python3" in the PATH
npm ERR! gyp verb `which` failed Error: not found: /usr/bin/python3
npm ERR! gyp verb `which` failed     at getNotFoundError (/var/www/html/nova-components/VideoImport/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/var/www/html/nova-components/VideoImport/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/var/www/html/nova-components/VideoImport/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /var/www/html/nova-components/VideoImport/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /var/www/html/nova-components/VideoImport/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /var/www/html/nova-components/VideoImport/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  /usr/bin/python3 Error: not found: /usr/bin/python3
npm ERR! gyp verb `which` failed     at getNotFoundError (/var/www/html/nova-components/VideoImport/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/var/www/html/nova-components/VideoImport/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/var/www/html/nova-components/VideoImport/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /var/www/html/nova-components/VideoImport/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /var/www/html/nova-components/VideoImport/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /var/www/html/nova-components/VideoImport/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "/usr/bin/python3", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/var/www/html/nova-components/VideoImport/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/var/www/html/nova-components/VideoImport/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/var/www/html/nova-components/VideoImport/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/var/www/html/nova-components/VideoImport/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /var/www/html/nova-components/VideoImport/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /var/www/html/nova-components/VideoImport/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /var/www/html/nova-components/VideoImport/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Linux 5.11.0-43-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/var/www/html/nova-components/VideoImport/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /var/www/html/nova-components/VideoImport/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home
```

**Comment by crynobone** [comment]
As stated in the document ation, please use node 14.

**Comment by flemming-petersen** [comment]
After downgrading to node 14 it also doesn't work and throws the same error.
