### ISSUE TITLE
VueJS 3.2.34 breaks nova-component compilation

### ISSUE THREAD

**Issue by ianrobertsFF** [laravel/nova-issues#4283]
- Laravel Version: v9.13.0
- Nova Version: v4.6.1
- PHP Version: v8.1.4
- Database Driver & Version: N/A
- Operating System and Version: Debian 11
- Browser type and version: N/A

### Description:
Vue 3.2.34 breaks something in the current latest versions of the default packages included in package.json for Nova Packages/Components

This gives the following error when you try to run `npm run prod` or `npm run dev`

```
[webpack-cli] Error: @vitejs/plugin-vue requires vue (>=3.2.13) or @vue/compiler-sfc to be present in the dependency tree.
    at Object.<anonymous> (/var/www/domain/nova-components/ResourceCards/node_modules/vue-loader/dist/compiler.js:14:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/domain/nova-components/ResourceCards/node_modules/vue-loader/dist/index.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

Looks like its the vitejs/plugin-vue thats causing the issue. But the upshot is anyone trying to create a new Asset, Card, Field, anything with the current package.json included in those stubs will receive the above error on latest versions of required packages. 

You can fix it by manually specifying `"@vue/compiler-sfc": "3.2.33",` instead of `"@vue/compiler-sfc": "^3.2.22",`

### Detailed steps to reproduce the issue on a fresh Nova installation:

- `php artisan nova:asset`
- Install node modules as prompted
- cd into the asset directory
- `npm run dev`

Error is presented

**Comment by ianrobertsFF** [comment]
I appreciate the underlying bug isnt with Nova, but the default workflow for creating any components presents this issue

**Comment by crynobone** [comment]
@ianrobertsFF do you by any change running on Node 12 for the project?

**Comment by ianrobertsFF** [comment]
@crynobone I did! For some reason nvm was set to 12, correcting that to 16 fixed the issue, thanks! Will close now.

**Comment by crynobone** [comment]
Vue.js commit [build: output es2020 (target node 14+) for cjs/server builds](https://github.com/vuejs/core/commit/cbeb9f2d7859edbaceee0c73d2b33c578a1ffb58) force Node 14+
