### ISSUE TITLE
Currency field applies fillUsing() transformation twice on column in Lens

### ISSUE THREAD

**Issue by DSpeichert** [laravel/nova-issues#5374]
- Laravel Version: 9.50.2 
- Nova Version:  4.22.1
- PHP Version: 8.1.3
- Database Driver & Version: 
- Operating System and Version: Ubuntu 22.04
- Browser type and version: Chrome Version 110.0.5481.178 (Official Build) (64-bit)
- Reproduction Repository: -

### Description:
It appears that when using the `Currency` field on a joined column from Lens custom query, the value is somehow passed twice through the `fillUsing(...)` callback defined in Currency's constructor.

As a result, when using major units (default) the value is usually multiplied by 100 (or whatever number of decimal positions for the chosen currency). However, when using minor units, it will get down to a fractional float value, which will then fail to be processed (minor units should be int):
> Brick\\Math\\Exception\\RoundingNecessaryException(code: 0): Rounding is necessary to represent the result of the operation at this scale.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Here is an illustrative excerpt from the Lens class. The `amount` field is not an actual column on the Resource that this Lens is attached to - it is obtained through joined table (`payments.amount as amount`). This is apparently what triggers that error - actual model columns work correctly.

This is very similar to the [official example in Nova documentation - MostValuableUsers](https://nova.laravel.com/docs/4.0/lenses/defining-lenses.html#overview) - except it uses a Text column to display the currency instead of Currency column.

```php
/**
     * Get the query builder / paginator for the lens.
     *
     * @param  \Laravel\Nova\Http\Requests\LensRequest  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return mixed
     */
    public static function query(LensRequest $request, $query)
    {
        return $request->withOrdering($request->withFilters(
            $query->select([
                'orders.id',
                'payments.amount as amount',
            ])
                ->join('payments', 'orders.id', '=', 'payments.order_id')
        ));
    }

    /**
     * Get the fields available to the lens.
     *
     * @param  NovaRequest  $request
     * @return array
     */
    public function fields(NovaRequest $request)
    {
        return [
            ID::make('ID', 'id')->sortable(),
            Currency::make('Amount', 'amount')
                ->asMinorUnits(),
        ];
    }
```

Relevant stacktrace:
```
#6 /app/vendor/laravel/nova/src/Fields/Currency.php(116): Brick\\Money\\Money::ofMinor()
#7 /app/vendor/laravel/nova/src/Fields/Currency.php(129): Laravel\\Nova\\Fields\\Currency->toMoneyInstance()
#8 /app/vendor/laravel/nova/src/Fields/Currency.php(91): Laravel\\Nova\\Fields\\Currency->formatMoney()
```

**Comment by crynobone** [comment]
Lens, Index and Detail doesn't use `fillUsing()`. The feature is only explicitly use on form submission.

**Comment by DSpeichert** [comment]
I was going to follow up with reproduction repository, but judging from your edits, it may no longer be needed. I was clearly wrong on the root cause but I'm glad you've found something. Let me know if you do need any more information from me.

**Comment by crynobone** [comment]
PR submitted and pending review.
