### ISSUE TITLE
`HasOne` field with relation resource containing `BelongsTo` call undefined method

### ISSUE THREAD

**Issue by kichetof** [laravel/nova-issues#5488]
- Laravel Version: 10.8.0
- Nova Version: 4.23.0
- PHP Version: 8.2.4
- Database Driver & Version: Laravel Sail

### Description:

I've a Model `Unit` with 2 relations `building` _(`BelongsTo`)_ and `setting` _(`HasOne`)_ methods.

When I visit Index/detail page from `Setting` or by visiting detail page of `Unit`, Nova try to load `building` method from `setting` model instead of `unit` model.

```log
[2023-04-21 10:12:14] local.ERROR: Call to undefined method App\Models\Setting::building() {"userId":636418,"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method App\\Models\\Setting::building() at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2335): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#2 /var/www/html/vendor/laravel/nova/src/Fields/BelongsTo.php(464): Illuminate\\Database\\Eloquent\\Model->__call()
#3 /var/www/html/vendor/laravel/nova/src/Fields/Field.php(1028): Laravel\\Nova\\Fields\\BelongsTo->sortableUriKey()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(427): Laravel\\Nova\\Fields\\Field->Laravel\\Nova\\Fields\\{closure}()
#5 /var/www/html/vendor/laravel/nova/src/Fields/Field.php(1010): with()
#6 /var/www/html/vendor/laravel/nova/src/Fields/BelongsTo.php(554): Laravel\\Nova\\Fields\\Field->jsonSerialize()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(427): Laravel\\Nova\\Fields\\BelongsTo->Laravel\\Nova\\Fields\\{closure}()
#8 /var/www/html/vendor/laravel/nova/src/Fields/BelongsTo.php(535): with()
#9 [internal function]: Laravel\\Nova\\Fields\\BelongsTo->jsonSerialize()
#10 /var/www/html/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(145): json_encode()
#11 [internal function]: Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->Laravel\\Telescope\\Storage\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(558): array_map()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(770): Illuminate\\Support\\Arr::map()
#14 /var/www/html/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(144): Illuminate\\Support\\Collection->map()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(235): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->Laravel\\Telescope\\Storage\\{closure}()
#16 /var/www/html/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(143): Illuminate\\Support\\Collection->each()
#17 /var/www/html/vendor/laravel/telescope/src/Telescope.php(666): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->store()
#18 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#19 /var/www/html/vendor/laravel/telescope/src/Telescope.php(291): call_user_func()
#20 /var/www/html/vendor/laravel/telescope/src/Telescope.php(658): Laravel\\Telescope\\Telescope::withoutRecording()
#21 /var/www/html/vendor/laravel/telescope/src/ListensForStorageOpportunities.php(65): Laravel\\Telescope\\Telescope::store()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1250): Illuminate\\Container\\Container->call()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(215): Illuminate\\Foundation\\Application->terminate()
#29 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
#30 /var/www/html/server.php(19): require_once('...')
#31 {main}
"} 
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

Unit Model

```php
public function building(): BelongsTo
{
    return $this->belongsTo(Building::class);
}

public function setting(): HasOne
{
    return $this->hasOne(Setting::class);
}
```

Unit Nova resource fields

```php
public function fields(NovaRequest $request): array
{
    return [
        ID::make()->sortable(),

        // some other fields without relation

        BelongsTo::make('Custom building', 'building', Building::class),

        HasOne::make('Some setting', 'setting', Setting::class),
    ];
}
```

___

Setting Model _(without direct relation with `building`, only though `unit`)_

```php
public function unit(): BelongsTo
{
    return $this->belongsTo(Unit::class);
}
```

Setting Nova resource fields

```php
public function fields(NovaRequest $request)
{
    return [
        ID::make()->sortable(),

        BelongsTo::make('Custom Unit', 'unit', Unit::class),

        // some other fields without relation
    ];
}
```

When I run command from Tinker, everything works fine:
> App\Models\Setting::find(1)->unit->building

Thanks a lot for your help
Christophe

**Comment by crynobone** [comment]
Hi there, I believe https://github.com/laravel/nova-dusk-suite already covers a similar use case without any bugs: https://github.com/laravel/nova-dusk-suite/blob/master/app/Models/Profile.php

Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by kichetof** [comment]
Hi @crynobone, effectively, everything should be covered by your test. I'll investigate why this method is called when HasOne is fired!

Thanks for pointing me to the tests!

**Comment by kichetof** [comment]
Found my issue, I wrote a mix between canSee and canSeeWhen that make the code crazy!

**Comment by korridor** [comment]
@kichetof I have the same problem. Stacktrace is almost identical. Could you explain in a bit more detail how you fix your problem? I just figured out for now that the error seams to disappear if Telescope is deactivated.

**Comment by kichetof** [comment]
Hi @korridor, I made a mistake by mixing `canSee` and `canSeeWhen` declaration (I didn't push my mistake to git, so I can't find exact fix as my commit was the fixed code)

**Comment by korridor** [comment]
@kichetof That's a shame, but thanks for your reply anyway! :)
