### ISSUE TITLE
Missing search results when using Laravel Scout with filters active

### ISSUE THREAD

**Issue by simon-roland** [laravel/nova-issues#5574]
- Laravel Version: 10.10.0
- Nova Version: 4.23.0
- PHP Version: 8.2.5
- Reproduction Repository: https://github.com/simon-roland/nova-scout-pagination-issue

### Description:

If you search using Laravel Scout and at the same time activate a filter, then sometimes no results are shown.

The bug is related to the per page option. Choosing a high 'per page' value, effectively disabling pagination, will then show the results that were missing.

It seems, that if the filter does not include any of the results from the first page, then no results are shown.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Follow the readme in the reproduction repo.

**Comment by crynobone** [comment]
Unable to run the resource:

```log
[2023-05-30 02:48:26] local.ERROR: Json deserialize error: unknown field `hitsPerPage`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `matches`, `filter`, `sort`, `facetsDistribution` at line 1 column 28 {"userId":26,"exception":"[object] (Meilisearch\\Exceptions\\ApiException(code: 400): Json deserialize error: unknown field `hitsPerPage`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `matches`, `filter`, `sort`, `facetsDistribution` at line 1 column 28 at /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php:199)
[stacktrace]
#0 /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php(168): Meilisearch\\Http\\Client->parseResponse()
#1 /var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php(100): Meilisearch\\Http\\Client->execute()
#2 /var/www/html/vendor/meilisearch/meilisearch-php/src/Endpoints/Indexes.php(204): Meilisearch\\Http\\Client->post()
#3 /var/www/html/vendor/laravel/scout/src/Engines/MeilisearchEngine.php(161): Meilisearch\\Endpoints\\Indexes->rawSearch()
#4 /var/www/html/vendor/laravel/scout/src/Engines/MeilisearchEngine.php(125): Laravel\\Scout\\Engines\\MeilisearchEngine->performSearch()
#5 /var/www/html/vendor/laravel/scout/src/Builder.php(406): Laravel\\Scout\\Engines\\MeilisearchEngine->paginate()
#6 /var/www/html/vendor/laravel/nova/src/Query/Builder.php(242): Laravel\\Scout\\Builder->paginate()
#7 /var/www/html/vendor/laravel/nova/src/Http/Requests/ResourceIndexRequest.php(21): Laravel\\Nova\\Query\\Builder->paginate()
#8 /var/www/html/vendor/laravel/nova/src/Http/Resources/IndexViewResource.php(19): Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest->searchIndex()
#9 /var/www/html/vendor/laravel/nova/src/Http/Resources/Resource.php(41): Laravel\\Nova\\Http\\Resources\\IndexViewResource->toArray()
#10 /var/www/html/vendor/laravel/nova/src/Http/Controllers/ResourceIndexController.php(19): Laravel\\Nova\\Http\\Resources\\Resource->toResponse()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Laravel\\Nova\\Http\\Controllers\\ResourceIndexController->__invoke()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#17 /var/www/html/vendor/laravel/nova/src/Http/Middleware/Authorize.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\Authorize->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): 
```

Are you sure it working locally when you create the reproduction repository?

**Comment by crynobone** [comment]
![image](https://github.com/laravel/nova-issues/assets/172966/f4898796-559d-441b-9426-0307fbb6d558)

I manage to run Laravel Scout with Algolia search engine without any issues, it seems that Meilisearch ignores `Laravel\Scout\Builder->$limit` coming from `Resource::$scoutSearchResults` when building the search queries. I believe there's an issue or incompatibility with Laravel Scout + Meilisearch at the moment.

**Comment by crynobone** [comment]
Confirmed this is an issue with Scout + Meilisearch and created an issue on the Laravel Scout repository.

https://github.com/laravel/scout/issues/742
