### ISSUE TITLE
Console error when Code field value is NULL

### ISSUE THREAD

**Issue by stuartcusackie** [laravel/nova-issues#5807]
- Laravel Version: 10.18.0
- Nova Version: 4.27.12
- PHP Version: 8.25
- Database Driver & Version: MySQL
- Operating System and Version: Windows 10
- Browser type and version Chrome

### Description:

Just a minor bug here. I can see a console error when the value for a Code field is NULL:

`Code::make('Embed Code', 'embed'),`

```
TypeError: Cannot read properties of null (reading 'split')
    at Re (codemirror.js:686:41)
    at Sa.splitLines (codemirror.js:6534:14)
    at Sa.<anonymous> (codemirror.js:6187:36)
    at Sa.setValue (codemirror.js:3987:22)
    at Proxy.mounted (CodeField.vue:37:8)
    at runtime-core.esm-bundler.js:2675:88
    at cn (runtime-core.esm-bundler.js:158:18)
    at un (runtime-core.esm-bundler.js:166:17)
    at Rr.t.__weh.t.__weh (runtime-core.esm-bundler.js:2655:19)
    at Sn (runtime-core.esm-bundler.js:325:26)
```

**Comment by crynobone** [comment]
You should add `nullable()` if the field can handle `null`.

**Comment by stuartcusackie** [comment]
This makes no difference. Please re-open.
