### ISSUE TITLE
Repeater fields don't work for MorphMany Relationship

### ISSUE THREAD

**Issue by blumewas** [laravel/nova-issues#5831]
- Laravel Version: 9.52.15
- Nova Version: 4.27.12
- PHP Version: 8.2.9

### Description:

In my Resource I had tried to create a repeater field for a polymorphic/morph-many relationship. If a polymorphic item is existent it's values are displayed and I can delete the entry.

But the button to add a row displays "Add undefined" and if I press it an the following error is printed in my browsers console:

```
TypeError: Cannot read properties of undefined (reading 'map')
    at setup (RepeaterRow.vue:89:37)
    at cn (runtime-core.esm-bundler.js:158:18)
    at runtime-core.esm-bundler.js:7236:25
    at ba (runtime-core.esm-bundler.js:7197:36)
    at B (runtime-core.esm-bundler.js:5599:7)
    at D (runtime-core.esm-bundler.js:5565:9)
    at y (runtime-core.esm-bundler.js:5040:11)
    at S (runtime-core.esm-bundler.js:5284:7)
    at M (runtime-core.esm-bundler.js:5499:7)
    at y (runtime-core.esm-bundler.js:5014:9)
```

The resource corresponding to the edit view where I get this behaviour:

```php
<?php

namespace App\Nova;

use App\Domains\Location\Location;
use App\Enums\DaysOfWeek;
use App\Nova\PickUpSlot as NovaPickUpSlot;
use App\Nova\Repeater\PickUpSlot;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Laravel\Nova\Fields\BelongsToMany;
use Laravel\Nova\Fields\Boolean;
use Laravel\Nova\Fields\DateTime;
use Laravel\Nova\Fields\FormData;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Markdown;
use Laravel\Nova\Fields\MorphMany;
use Laravel\Nova\Fields\Number;
use Laravel\Nova\Fields\Repeater;
use Laravel\Nova\Fields\Select;
use Laravel\Nova\Fields\Slug;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;
use Laravel\Nova\Panel;
use Mindtwo\DeliveryMailExport\DeliveryMailExport;
use Outl1ne\NovaSimpleRepeatable\SimpleRepeatable;

class Locations extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = Location::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'title';

    /**
     * Indicates whether Nova should check for modifications between viewing and updating a resource.
     *
     * @var bool
     */
    public static $trafficCop = false;

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
        'title',
        'slug',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     *
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make('ID', 'id')
                ->hideFromIndex()
                ->hideWhenCreating()
                ->hideWhenUpdating()
                ->sortable(),

            [...fields]

            Panel::make('Pick Up', $this->getPickUpFields()),
            
            [...more panels and fiels]
        ];
    }

    protected function getPickUpFields(): array
    {
        return [
            [...other fields]

            // MorphMany::make('Label', 'pickUpSlots', NovaPickUpSlot::class),

            Repeater::make('Label', 'pick_up_slots')
                ->repeatables([
                    PickUpSlot::class,
                ])
                ->asHasMany(NovaPickUpSlot::class)
                ->uniqueField('id'),
        ];
    }

    
}
```

Repeater Field:

```php
<?php

namespace App\Nova\Repeater;

use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Repeater\Repeatable;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;

class PickUpSlot extends Repeatable
{
    public static $model = \App\Domains\Location\PickUpSlot::class;

    /**
     * Get the fields displayed by the repeatable.
     *
     * @return array
     */
    public function fields(NovaRequest $request)
    {
        return [
            ID::hidden('id'),

            Text::make('From', 'from')
                ->rules([
                    'required',
                    function ($attribute, $value, $fail) {
                        if (! preg_match('/^[0-9]{1,2}:[0-9]{2}(:[0-9]{2})?$/', $value)) {
                            $fail('Ungültige Zeitangabe');
                        }
                    },
                ])
                ->resolveUsing(function ($item) {
                    if (empty($item)) {
                        return '';
                    }

                    $item = explode(':', $item);

                    return "{$item[0]}:{$item[1]}";
                }),

            Text::make('To', 'to')
                ->rules([
                    'required',
                    function ($attribute, $value, $fail) {
                        if (! preg_match('/^[0-9]{1,2}:[0-9]{2}(:[0-9]{2})?$/', $value)) {
                            $fail('Ungültige Zeitangabe');
                        }
                    },
                ])
                ->resolveUsing(function ($item) {
                    if (empty($item)) {
                        return '';
                    }

                    $item = explode(':', $item);

                    return "{$item[0]}:{$item[1]}";
                }),
        ];
    }

    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return 'Pick Up Slots';
    }

    /**
     * Get the displayable singular label of the resource.
     *
     * @return string
     */
    public static function singularLabel()
    {
        return 'Pick Up Slot';
    }
}
```

Resource for polymorphic model:

```php
<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\MorphTo;
use Laravel\Nova\Fields\Text;

class PickUpSlot extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Domains\Location\PickUpSlot::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'id';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [];

    /**
     * Indicates if the resource should be displayed in the sidebar.
     *
     * @var bool
     */
    public static $displayInNavigation = false;

    /**
     * Indicates if the resource should be globally searchable.
     *
     * @var bool
     */
    public static $globallySearchable = false;

    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return 'Pick Up Slots';
    }

    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function singularLabel()
    {
        return 'Pick Up Slot';
    }

    /**
     * Get the fields displayed by the resource.
     *
     *
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::hidden('id'),

            MorphTo::make('PickUpSlotable')
                ->types([
                    \App\Nova\Locations::class,
                    \App\Nova\Sublocation::class,
                ]),

            [...same fields as repeater field]
    }
}
```

Class for my polymorphic model:

```php
<?php

namespace App\Domains\Location;

use Carbon\CarbonInterval;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Support\Carbon;

/**
 * @property int $id
 * @property string $from
 * @property string $to
 * @property \Carbon\CarbonInterval $intervals
 * @property array $availableSlotsToday
 * @property array $availableSlots
 */
class PickUpSlot extends Model
{
    /**
     * No timestamps needed.
     */
    public $timestamps = false;

    /**
     * The attributes that are not mass assignable.
     */
    protected $protected = [
        'id',
    ];

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'from',
        'to',
    ];

    /**
     * Get the parent commentable model (post or video).
     */
    public function pickUpSlotAble(): MorphTo
    {
        return $this->morphTo();
    }

  [...methods and attributes]
}
```

**Comment by crynobone** [comment]
There's only `HasMany` and `JSON` preset as explained in the documentation

**Comment by blumewas** [comment]
ok. sorry completely miss-read that there.
