### ISSUE TITLE
Search no longer works after upgrading Node and NPM

### ISSUE THREAD

**Issue by brada1703** [laravel/nova-issues#6057]
- Laravel Version: 9.52.16
- Nova Version: 4.32.1
- PHP Version: 8.2.12
- Node Version: 21.1.0
- NPM Version: 10.2.0

### Description:

After upgrading to Node v21.1 and NPM v10.2, I can no longer search. The search fails with an error `TypeError: Cannot read properties of null (reading 'emitsOptions')`.

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Create a new resource with searchable columns
- Visit the resource and search for a value (search input for the index table)
- Open developer tools to view error:

```
runtime-core.esm-bundler.js:226 TypeError: Cannot read properties of null (reading 'parentNode')
    at remove (runtime-dom.esm-bundler.js:13:30)
    at a (runtime-core.esm-bundler.js:5545:13)
    at H (runtime-core.esm-bundler.js:5563:13)
    at $ (runtime-core.esm-bundler.js:5521:17)
    at Object.remove (runtime-core.esm-bundler.js:5886:21)
    at $ (runtime-core.esm-bundler.js:5505:28)
    at G (runtime-core.esm-bundler.js:5622:13)
    at $ (runtime-core.esm-bundler.js:5512:17)
    at K (runtime-core.esm-bundler.js:5593:13)
    at $ (runtime-core.esm-bundler.js:5494:13)
...
runtime-core.esm-bundler.js:226 TypeError: Cannot read properties of null (reading 'nextSibling')
    at nextSibling (runtime-dom.esm-bundler.js:36:31)
    at Z (runtime-core.esm-bundler.js:5632:16)
    at g (runtime-core.esm-bundler.js:4457:22)
    at L (runtime-core.esm-bundler.js:4806:13)
    at T (runtime-core.esm-bundler.js:4714:13)
    at w (runtime-core.esm-bundler.js:4569:13)
    at g (runtime-core.esm-bundler.js:4486:21)
    at we.fn (runtime-core.esm-bundler.js:5107:17)
    at we.run (reactivity.esm-bundler.js:167:25)
    at P (runtime-core.esm-bundler.js:4968:26)
```

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by brada1703** [comment]
I was able to solve the issue by removing and reinstalling Nova. I think there was some issue when I updated the package.

**Comment by vesper8** [comment]
I was having this issue too, it was because of some overrides I had setup to do things like place the CRUD icons on the left inside of the right, and to make the search results cmd-clickable to open in a new tab. I guess one of the recent updates is conflicting with my overrides.

Now that I've removed all my overrides the error has gone away.. but for some weird reason the search results box now disappears after it appears.
