### ISSUE TITLE
[Bug] Tag Field is broken

### ISSUE THREAD

**Issue by muhammadsaeedparacha** [laravel/nova-issues#6065]
- Laravel Version: #.#.#
- Nova Version: 4.32.2
- PHP Version: #.#.#
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
Tag Form Field is broken,
I do not see the input field, only existing values
```
Tag::make('Roles', 'roles', Role::class)->preload(),
Tag::make('Teams')
```

<img width="1680" alt="Screenshot 2023-11-24 at 9 55 49 AM" src="https://github.com/laravel/nova-issues/assets/2680384/dcab4999-52ef-492e-8ae6-f0c9471c6cb7">

It doesn't show the field.

Console error says:
```
runtime-core.esm-bundler.js:226 ReferenceError: Cannot access 's' before initialization
    at setup (SearchSearchInput.vue:89:52)
    at an (runtime-core.esm-bundler.js:158:18)
    at runtime-core.esm-bundler.js:7289:25
    at wa (runtime-core.esm-bundler.js:7250:36)
    at L (runtime-core.esm-bundler.js:5646:7)
    at O (runtime-core.esm-bundler.js:5612:9)
    at y (runtime-core.esm-bundler.js:5087:11)
    at E (runtime-core.esm-bundler.js:5331:7)
    at C (runtime-core.esm-bundler.js:5238:7)
    at A (runtime-core.esm-bundler.js:5203:7)
```

on this line in SearchSearchInput
```
const debouncer = debounce(callback => callback(), props.debounce)
```

**Comment by davidhemphill** [comment]
This has been fixed and a new release has been pushed. 👍
