### ISSUE TITLE
Login page not working after deployment

### ISSUE THREAD

**Issue by AbdelkaderBah** [laravel/nova-issues#6465]
- Laravel Version: 10.48.12
- Nova Version: 4.34.3
- PHP Version: 8.2.20
- Database Driver & Version:
- Operating System and Version: Laravel Forge
- Browser type and version: Google chrome 126.0.6478.182

### Description:
Nova is working locally without any issues, once I have deployed it to forge, I am getting a blank page,
with the following console issue (the only one).
```
app.js?id=4f1ec3789b86ed89a9a1900e986b95e6:1 Uncaught TypeError: Cannot read properties of undefined (reading 'use')
    at br.registerStoreModules (app.js?id=4f1ec3789b86ed89a9a1900e986b95e6:1:74154)
    at br.liftOff (app.js?id=4f1ec3789b86ed89a9a1900e986b95e6:1:71871)
    at <anonymous>:2:14
    at t.activateScript (rocket-loader.min.js:1:11855)
    at rocket-loader.min.js:1:11052
    at t.run (rocket-loader.min.js:1:11259)
    at P (rocket-loader.min.js:1:3128)
    at Object.callback (rocket-loader.min.js:1:2851)
    at t.run (rocket-loader.min.js:1:11340)
    at rocket-loader.min.js:1:11156

```

![image](https://github.com/user-attachments/assets/3ae58c3d-d3ab-4522-bbfe-08d39d4900ab)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Deploy Nova to forge.

**Comment by AbdelkaderBah** [comment]
Refering to the previous issues, it was caused by Cloudflare Rocket loader.

*Solution*:
1. Create a new Page rule
2. set the URL you want e.g: ```somewhere.example.com/*```
3. Choose Rocket league (don't turn it on)
4. Save
