### ISSUE TITLE
General error: 1205 Lock wait timeout exceeded in Nova Action

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#810]
- Laravel Version: v5.7.8
- Nova Version: v1.1.4
- PHP Version: 7.2

### Description:

Here is my error stack:

```
[2018-10-07 10:41:07] local.ERROR: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: update `nova_action_events` set `status` = finished, `updated_at` = 2018-10-07 10:40:16 where `batch_id` = 8bf5d7ab-45b1-4c48-aff8-5ae54080701b and `status` not in (finished, failed)) {"userId":"07166164102539","email":"phoenixg@movableppp.com","exception":"[object] (Illuminate\Database\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: update `nova_action_events` set `status` = finished, `updated_at` = 2018-10-07 10:40:16 where `batch_id` = 8bf5d7ab-45b1-4c48-aff8-5ae54080701b and `status` not in (finished, failed)) at /Users/phx/mine/projects/php/my-nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\DBAL\Driver\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction at /Users/phx/mine/projects/php/my-nova/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:144, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction at /Users/phx/mine/projects/php/my-nova/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:142)
[stacktrace]
#0 /Users/phx/mine/projects/php/my-nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('update `nova_ac...', Array, Object(Closure))
#1 /Users/phx/mine/projects/php/my-nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php(490): Illuminate\Database\Connection->run('update `nova_ac...', Array, Object(Closure))
#2 /Users/phx/mine/projects/php/my-nova/vendor/laravel/framework/src/Illuminate/Database/Connection.php(423): Illuminate\Database\Connection->affectingStatement('update `nova_ac...', Array)
...
#83 /Users/phx/mine/projects/php/my-nova/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#84 {main}
"} 
```

### Steps To Reproduce:

```PHP
<?php

namespace App\Nova\Actions;

use App\Traits\EloquentBootstrap;
use Artisan;
use Illuminate\Bus\Queueable;
use Laravel\Nova\Actions\Action;
use Illuminate\Support\Collection;
use Laravel\Nova\Fields\ActionFields;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Laravel\Nova\Fields\Text;

class RerunTheScript extends Action
{
    use InteractsWithQueue, Queueable, SerializesModels;

    use EloquentBootstrap;

    public $name = 'Rerun the script';

    public function handle(ActionFields $fields, Collection $models)
    {
        $this->bootEloquent();
        return Action::message('success');
    }

}

```

Here is my trait:

```PHP
namespace App\Traits;
use App\Utils\Encryption\Encryption;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Database\Capsule\Manager as Capsule;

trait EloquentBootstrap
{
    public function bootEloquent()
    {
        $capsule = new Capsule;

        $capsule->setAsGlobal();

        $capsule->setEventDispatcher(new Dispatcher(new Container));

        foreach (config('database.connections') as $connection => &$db) {
            $capsule->addConnection($db, $connection);
            Capsule::connection($connection)->enableQueryLog();
        }

        $capsule->bootEloquent();
    }
}

```

If I remove the trait, that's OK, but I have to use the manually eloquent booter, because my Eloquent models are a standalone composer project.

I've tried call it in my laravel route directly, it works:

```PHP
Artisan::call('the-script-name:check', [
    'date' => '2018-09-06',
]);
```

But If I write the Artisan call in Nova Action's `handle` method, it occurred the `lock wait timeout` error. Why? How to solve that?

**Comment by phoenixg** [comment]
I found it's no relation with my eloquent booter, after I changed to below code, the problem solved.

  ```PHP
// nova/src/Actions/ActionEvent.php
public static function markBatchAsFinished($batchId)
{
        return true;
}
```

But's it seems like a bug now apparently.

**Comment by phoenixg** [comment]
Seems ok now, although I don't know why.

**Comment by pawanyd14** [comment]
[``](`[url](`[url](`[url](`[url](`[url](url)`)`)`)`)`)

**Comment by clementmas** [comment]
For future reference, I had the same error when running a slow action (making https requests).

I fixed it by preventing Nova from logging the event in the database:

```php
// app\Nova\Actions\MyLongAction.php

/**
 * Indicates if need to skip log action events for models.
 */
public $withoutActionEvents = true;
```
