### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to Laravel\Nova\Resource::resolveFields() must be an instance of Laravel\Nova\Http\Requests\NovaRequest, instance of Illuminate\Http\Request given

### ISSUE THREAD

**Issue by affektde** [laravel/nova-issues#88]
I know that there is something wrong in poly-morph relation definition, but I can't debug it.

Is there a solution to know what's wrong when this exception is thrown? Or is something planed to improve error stack trace?

```Php
Uncaught TypeError: Argument 1 passed to Laravel\Nova\Resource::resolveFields() 
must be an instance of Laravel\Nova\Http\Requests\NovaRequest, instance of Illuminate\Http\Request given, called in /data/www/vendor/laravel/nova/src/Resource.php on line 350 and defined in /data/www/vendor/laravel/nova/src/ResolvesFields.php:150↵
Stack trace:
↵#0 /data/www/vendor/laravel/nova/src/Resource.php(350): Laravel\Nova\Resource->resolveFields(Object(Illuminate\Http\Request))
↵#1 [internal function]: Laravel\Nova\Resource->jsonSerialize()
↵#2 /data/www/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(71): json_encode(Array, 0)
↵#3 /data/www/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\Http\JsonResponse->setData(Array)
↵#4 /data/www/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(31): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array, 400, Array)
↵#5 /data/www/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(83): Illuminate\Http\JsonResponse->__constr
```

It's thrown, when I add a poly-morph relation into my Nova Model:

```Php
MorphTo::make('Commentable')->types([
    Post::class,
    Video::class,
])
```

Does anyone have same experiences?

**Comment by mbardelmeijer** [comment]
Having the same issue. Also using a MorphTo and unable to load the index screen.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
